steps:

- name: 'maven:3.6.1-jdk-11'
  id: 'MavenBuild'
  entrypoint: 'mvn'
  args: ['-B', '-q', 'clean', 'install']
  
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-spring-initializr-service:latest', '.']

- name: 'docker'
  args: ['tag',
    'gcr.io/$PROJECT_ID/my-spring-initializr-service:latest',
    'gcr.io/$PROJECT_ID/my-spring-initializr-service:fancy']

images: ['gcr.io/$PROJECT_ID/my-spring-initializr-service:latest', 
  'gcr.io/$PROJECT_ID/my-spring-initializr-service:fancy']