kind: Deployment
apiVersion: apps/v1
metadata:
  name: initializr-deployment
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  minReadySeconds: 5
  template:
    spec:
      containers:
        - name: initializr-service
          image: gcr.io/pingpong-site1-gcp-demo/my-spring-initializr-service:fancy
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 250Mi
            limits:
              cpu: 2.0
              memory: 500Mi
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 1
            timeoutSeconds: 1
            httpGet:
              path: /actuator/health
              port: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1